name: Dev Deployment

on:
  push:
    branches:
      - master
      # - development

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout UAT branch for Production release
      - name: Checkout UAT branch
        uses: actions/checkout@v3
        with:
          ref: master
          # ref: development


      # 2️⃣ Show repo structure (optional)
      - name: Show repo file structure
        run: |
          echo "Workspace content:"
          ls -R .

      # 3️⃣ Ensure /dev-bin exists on Production server
      - name: Ensure /dev-bin directory exists on PROD server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          # key: ${{ secrets.DEV_SSH_KEY }}
          password: ${{ secrets.DEV_PASSWORD }}
          script: |
            sudo mkdir -p /dev-bin
            sudo chmod 777 /dev-bin
            echo "/dev-bin directory ready"

      # 4️⃣ Upload deployment folders to production
      - name: Upload folders to Production server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          # key: ${{ secrets.DEV_SSH_KEY }}
          password: ${{ secrets.DEV_PASSWORD }}
          source: "bdf-datamaps,custom-datamaps,ingestion-manager,scenarios,controlm-scripts"
          target: "/opt/fatack_uti/upload_temp"
          strip_components: 0

      # 5️⃣ Upload Production deployment script
      - name: Upload production deployment script
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          # key: ${{ secrets.DEV_SSH_KEY }}
          password: ${{ secrets.DEV_PASSWORD }}
          source: "./.github/bin/dev-deploy.sh"
          target: "/dev-bin"
          strip_components: 2

      # 6️⃣ Run deployment script on Production server
      - name: Run deployment script on Production
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          # key: ${{ secrets.DEV_SSH_KEY }}
          password: ${{ secrets.DEV_PASSWORD }}
          script: |
            echo "Listing /dev-bin before running script:"
            ls -la /dev-bin/bin
            sudo chmod +x /dev-bin/bin/dev-deploy.sh
            sudo /dev-bin/bin/dev-deploy.sh
