name: Production Deployment

on:
  workflow_dispatch:

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout UAT branch for Production release
      - name: Checkout UAT branch
        uses: actions/checkout@v3
        with:
          # ref: master
          ref: uat

      # 2️⃣ Show repo structure (optional)
      - name: Show repo file structure
        run: |
          echo "Workspace content:"
          ls -R .

      # 3️⃣ Ensure /prod-bin exists on Production server
      - name: Ensure /prod-bin directory exists on PROD server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          # key: ${{ secrets.PROD_SSH_KEY }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            sudo mkdir -p /prod-bin
            sudo chmod 777 /prod-bin
            echo "/prod-bin directory ready"

      # 4️⃣ Upload deployment folders to production
      - name: Upload folders to Production server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          # key: ${{ secrets.PROD_SSH_KEY }}
          password: ${{ secrets.PROD_PASSWORD }}
          source: "bdf-datamaps,custom-datamaps,ingestion-manager,scenarios,controlm-scripts"
          target: "/opt/fatack_uti/upload_temp"
          strip_components: 0

      # 5️⃣ Upload Production deployment script
      - name: Upload production deployment script
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          # key: ${{ secrets.PROD_SSH_KEY }}
          password: ${{ secrets.PROD_PASSWORD }}
          source: "./.github/bin/prod-deploy.sh"
          target: "/prod-bin"
          strip_components: 2

      # 6️⃣ Run deployment script on Production server
      - name: Run deployment script on Production
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          # key: ${{ secrets.PROD_SSH_KEY }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            echo "Listing /prod-bin before running script:"
            ls -la /prod-bin/bin
            sudo chmod +x /prod-bin/bin/prod-deploy.sh
            sudo /prod-bin/bin/prod-deploy.sh
