name: QA Deployment

on:
  push:
    branches:
      - master
      # - qatest

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout UAT branch for Production release
      - name: Checkout qatest branch
        uses: actions/checkout@v3
        with:
          ref: master
          # ref: qatest


      # 2️⃣ Show repo structure (optional)
      - name: Show repo file structure
        run: |
          echo "Workspace content:"
          ls -R .

      # 3️⃣ Ensure /qa-bin exists on Production server
      - name: Ensure /qa-bin directory exists on PROD server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          # key: ${{ secrets.DEV_SSH_KEY }}
          password: ${{ secrets.DEV_PASSWORD }}
          script: |
            sudo mkdir -p /qa-bin
            sudo chmod 777 /qa-bin
            echo "/qa-bin directory ready"

      # 4️⃣ Upload deployment folders to production
      - name: Upload folders to Production server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          # key: ${{ secrets.DEV_SSH_KEY }}
          password: ${{ secrets.DEV_PASSWORD }}
          source: "bdf-datamaps,custom-datamaps,ingestion-manager,scenarios,controlm-scripts"
          target: "/opt/fatack_uti/upload_temp"
          strip_components: 0


      # 5️⃣ Upload Production deployment script
      - name: Upload production deployment script
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          # key: ${{ secrets.DEV_SSH_KEY }}
          password: ${{ secrets.DEV_PASSWORD }}
          source: "./.github/bin/qa-deploy.sh"
          target: "/qa-bin"
          strip_components: 2

      # 6️⃣ Run deployment script on Production server
      - name: Run deployment script on Production
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          # key: ${{ secrets.DEV_SSH_KEY }}
          password: ${{ secrets.DEV_PASSWORD }}
          script: |
            echo "Listing /qa-bin before running script:"
            ls -la/qa-bin/bin
            sudo chmod +x/qa-bin/bin/qa-bin.sh
            sudo/qa-bin/bin/qa-bin.sh
